import { Link } from "react-router-dom";
import { useImportRuns } from "@/services/production/hooks";

const statusLabel = { PREVIEWED: "Előnézet", APPLIED: "DRAFT betöltve", REJECTED: "Elutasítva" } as const;

/** Domain-specific import audit view. A platform DataTable can replace its
 * presentation later without changing this Doorstar workflow or API. */
export function ImportInboxPage() {
  const { data: runs = [], isLoading, isError } = useImportRuns();
  return <main className="orders-page"><div className="orders-content">
    <header className="orders-hero"><div><p>Adatátállás</p><h1>Import Inbox</h1><span>Excel/PDF előnézetek és tesztsémás DRAFT-betöltések. A forrásfájlok változatlanul megmaradnak.</span></div><Link className="doorstar-home-primary-action" to="/orders">Rendelések</Link></header>
    {isLoading ? <div className="orders-state">Importok betöltése…</div> : isError ? <div className="orders-state">Az Import Inbox nem érhető el. Ellenőrizd a termelési szolgáltatást.</div> : runs.length === 0 ? <section className="order-document-card"><div className="order-document-heading"><div><span>Üres inbox</span><h2>Még nincs regisztrált importfutás</h2><p>Az adatgyűjtő előnézetei itt jelennek meg, miután a tesztsémában regisztrálta őket.</p></div></div></section> : <section className="order-revision-list" aria-label="Importfutások">{runs.map((run) => { const revision = run.revisions[0]; return <article className="order-revision" key={run.id}><header><div><span>{statusLabel[run.status]}</span><h2>{revision?.order.project.name ?? run.previewArtifact}</h2></div><div className="order-register-states"><b className={`order-status order-status-${run.status === "APPLIED" ? "approved" : run.status === "REJECTED" ? "superseded" : "draft"}`}>{statusLabel[run.status]}</b></div></header><div className="order-revision-meta"><span>{run.candidateCount} előnézeti rekord</span><span>{run._count.candidates} kereshető jelölt</span><span>{run._count.deadlineObservations} határidő-megfigyelés</span><span>Cél: {run.targetSchema}</span><span>{new Intl.DateTimeFormat("hu-HU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(run.createdAt))}</span></div>{revision && <div className="order-position-summary"><div><strong>{revision.order.project.key}</strong><span>R{String(revision.revision).padStart(2, "0")} · {revision.intakeStage}</span><span>{revision._count.positions} pozíció · {revision._count.documents} dokumentum</span><span>{revision._count.feedback} visszajelzés</span></div></div>}<div className="order-audit-list"><div><b>Mapping</b><span>{run.profileVersion}</span><code>{run.sourceFingerprint.slice(0, 12)}…</code><Link to={`/imports/${encodeURIComponent(run.id)}`}>Bizonyítékok megnyitása →</Link></div>{revision && <div><b>Kapcsolt DRAFT</b><span>{revision.order.project.key}</span><span>R{String(revision.revision).padStart(2, "0")}</span><Link to={`/orders/${encodeURIComponent(revision.order.project.key)}`}>Rendelés megnyitása →</Link></div>}</div></article>; })}</section>}
  </div></main>;
}
