import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAddOrderDocument, useAdvanceOrderIntakeStage, useApproveOrderRevision, useCreateOrderFeedback, useOrderFeedback, useProductionOrder, useRequestOrderReview, useResolveOrderFeedback, useResolveOrderPositionEvidence, useReviewManufacturedItem } from "@/services/production/hooks";
import { useUiStore } from "@/store/uiStore";
import { canApproveOrder, canCompleteSurvey, canCreateSalesOrder, canRequestOrderReview, canSendToTechnicalPreparation } from "@/lib/roles";
import type { OrderDocumentKind, OrderFeedbackCategory, OrderIntakeStage, OrderRevisionStatus, ProductionOrderPosition } from "@/services/production/types";
import { OrderPositionEvidenceList } from "@/components/orders/OrderPositionEvidenceList";
import { ManufacturedItemsPanel } from "@/components/orders/ManufacturedItemsPanel";

const statusLabel: Record<OrderRevisionStatus, string> = { DRAFT: "Piszkozat", REVIEW: "Ellenőrzés alatt", APPROVED: "Jóváhagyott", SUPERSEDED: "Leváltott" };
const intakeLabel: Record<OrderIntakeStage, string> = { SALES_DRAFT: "Sales piszkozat", SALES_DOCUMENTS_RECEIVED: "Dokumentumok átvéve", SURVEY_PENDING: "Felmérésre vár", SURVEY_COMPLETED: "Felmérés kész", SURVEY_EXCEPTION_REVIEW: "Felmérési kivétel", TECHNICAL_PREPARATION: "Műszaki előkészítés" };
const documentKindLabel: Record<OrderDocumentKind, string> = { SALES_ORDER: "Megrendelés", SURVEY: "Felmérés", DRAWING: "Rajz", OTHER: "Egyéb" };
function dimensions(position: ProductionOrderPosition) {
  const opening = [position.openingWidthMm, position.openingHeightMm, position.openingDepthMm];
  const door = [position.doorWidthMm, position.doorHeightMm, position.doorThicknessMm];
  const openingText = opening.every((value) => value != null) ? `Falnyílás: ${opening.join(" × ")} mm` : "Falnyílás: felméréskor pontosítandó";
  const doorText = door.every((value) => value != null) ? `Ajtólap: ${door.join(" × ")} mm` : "Ajtólap: felméréskor pontosítandó";
  return `${openingText} · ${doorText}`;
}

export function OrderDetailPage() {
  const { projectKey = "" } = useParams();
  const role = useUiStore((state) => state.role);
  const { data: order, isLoading, isError } = useProductionOrder(projectKey);
  const advance = useAdvanceOrderIntakeStage(projectKey);
  const addDocument = useAddOrderDocument(projectKey);
  const requestReview = useRequestOrderReview(projectKey);
  const approve = useApproveOrderRevision(projectKey);
  const feedback = useOrderFeedback(projectKey, order?.revisions[0]?.revision);
  const reportFeedback = useCreateOrderFeedback(projectKey, order?.revisions[0]?.revision);
  const resolveFeedback = useResolveOrderFeedback(projectKey, order?.revisions[0]?.revision);
  const resolveEvidence = useResolveOrderPositionEvidence(projectKey, order?.revisions[0]?.revision);
  const reviewManufacturedItem = useReviewManufacturedItem(projectKey, order?.revisions[0]?.revision);
  const [documentName, setDocumentName] = useState(""); const [documentPath, setDocumentPath] = useState("");
  const [documentKind, setDocumentKind] = useState<OrderDocumentKind>("SALES_ORDER"); const [message, setMessage] = useState<string | null>(null);
  const [approvalNote, setApprovalNote] = useState("");
  const [feedbackCategory, setFeedbackCategory] = useState<OrderFeedbackCategory>("DATA_QUALITY"); const [feedbackMessage, setFeedbackMessage] = useState("");
  if (isLoading) return <main className="orders-page"><div className="orders-content"><div className="orders-state">Rendelés betöltése…</div></div></main>;
  if (isError || !order) return <main className="orders-page"><div className="orders-content"><div className="orders-state">A rendelés nem érhető el, vagy a termelési szolgáltatás nem fut.</div></div></main>;
  const latest = order.revisions[0]; const canSales = canCreateSalesOrder(role); const canPrepare = canCompleteSurvey(role);
  async function receiveDocuments() { if (!latest) return; try { await advance.mutateAsync({ revision: latest.revision, stage: "SALES_DOCUMENTS_RECEIVED" }); await advance.mutateAsync({ revision: latest.revision, stage: "SURVEY_PENDING" }); } catch { setMessage("A dokumentumátvételhez legalább egy dokumentumhivatkozást rögzíts."); } }
  async function addReference() { if (!latest || !documentName.trim() || !documentPath.trim()) { setMessage("Add meg a dokumentum nevét és a Sales-forráshoz viszonyított útvonalát."); return; } try { await addDocument.mutateAsync({ revision: latest.revision, input: { source: "LEGACY_FOLDER", kind: documentKind, displayName: documentName.trim(), relativePath: documentPath.trim() } }); setDocumentName(""); setDocumentPath(""); setMessage(null); } catch { setMessage("Csak relatív útvonal rögzíthető; teljes helyi elérési út és .. nem használható."); } }
  async function sendToPreparation() { if (latest) await advance.mutateAsync({ revision: latest.revision, stage: "TECHNICAL_PREPARATION" }); }
  async function review() { if (!latest) return; try { await requestReview.mutateAsync({ revision: latest.revision, note: "Műszaki előkészítés teljes." }); } catch { setMessage("Review-ra csak teljes felméréssel és dokumentumhivatkozással küldhető a rendelés."); } }
  async function approveRevision() { if (!latest || approvalNote.trim().length < 3) { setMessage("A jóváhagyáshoz rövid indoklás szükséges."); return; } try { await approve.mutateAsync({ revision: latest.revision, note: approvalNote.trim() }); setApprovalNote(""); setMessage(null); } catch { setMessage("A jóváhagyás nem sikerült; a revízió állapotát ellenőrizd újra."); } }
  async function reportIssue() { if (feedbackMessage.trim().length < 3) { setMessage("Írd le röviden a hibát vagy a hiányzó adatot."); return; } try { await reportFeedback.mutateAsync({ category: feedbackCategory, message: feedbackMessage.trim() }); setFeedbackMessage(""); setMessage(null); } catch { setMessage("A jelzés rögzítése nem sikerült."); } }

  return <main className="orders-page"><div className="orders-content">
    <header className="orders-hero"><div><p>Rendelés / {projectKey}</p><h1>Rendelési adatlap</h1><span>Sales, felmérés, műszaki előkészítés, review és jóváhagyás külön adatkapu.</span></div><Link className="doorstar-home-primary-action" to="/orders/new">Új sales rendelés</Link></header>
    {latest && <section className="order-workflow-card"><div><span>Aktuális adatkapu</span><h2>{intakeLabel[latest.intakeStage]} · {statusLabel[latest.status]}</h2><p>Az approval egy konkrét tartalmi pillanatképet rögzít. Csak az így jóváhagyott revízióból készülhet később kalkuláció és gyártási kiadás.</p></div><div className="order-workflow-actions">{canSales && latest.intakeStage === "SALES_DRAFT" && <button className="order-button order-button-primary" onClick={() => void receiveDocuments()} disabled={advance.isPending}>Dokumentumok átvéve → felmérés</button>}{canPrepare && latest.intakeStage === "SURVEY_PENDING" && <Link className="order-button order-button-primary" to={`/orders/${encodeURIComponent(projectKey)}/survey`}>Felmérés megnyitása</Link>}{canSendToTechnicalPreparation(role) && latest.intakeStage === "SURVEY_COMPLETED" && <button className="order-button order-button-primary" onClick={() => void sendToPreparation()} disabled={advance.isPending}>Műszaki előkészítésre adás</button>}{canRequestOrderReview(role) && latest.status === "DRAFT" && latest.intakeStage === "TECHNICAL_PREPARATION" && <button className="order-button order-button-primary" onClick={() => void review()} disabled={requestReview.isPending}>Review-ra küldés</button>}</div></section>}
    {latest?.status === "REVIEW" && canApproveOrder(role) && <section className="order-approval-card"><div><span>Jóváhagyási kapu</span><h2>Független ellenőrzés</h2><p>A jóváhagyás lezárja ezt a revíziót és SHA-256 tartalmi ujjlenyomatot rögzít.</p></div><input value={approvalNote} onChange={(event) => setApprovalNote(event.target.value)} placeholder="Jóváhagyás indoklása *" /><button className="order-button order-button-primary" onClick={() => void approveRevision()} disabled={approve.isPending}>Jóváhagyás</button></section>}
    {latest && <section className="order-document-card"><div className="order-document-heading"><div><span>Dokumentumkapu</span><h2>Sales dokumentumhivatkozások</h2><p>Forrás: <code>01 - Megrendelés</code>. Relatív útvonalat adj meg, például <code>DSMR 24181 Projekt/Megrendelés.pdf</code>.</p></div></div>{canSales && latest.status === "DRAFT" && <div className="order-document-form"><input value={documentName} onChange={(event) => setDocumentName(event.target.value)} placeholder="Dokumentum neve" /><select value={documentKind} onChange={(event) => setDocumentKind(event.target.value as OrderDocumentKind)}>{Object.entries(documentKindLabel).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select><input value={documentPath} onChange={(event) => setDocumentPath(event.target.value)} placeholder="Projekt mappa/Fájl.pdf" /><button className="order-button order-button-secondary" onClick={() => void addReference()} disabled={addDocument.isPending}>Hivatkozás rögzítése</button></div>}{latest.documents.length === 0 ? <p className="order-document-empty">Még nincs rögzített dokumentumhivatkozás.</p> : <ul className="order-document-list">{latest.documents.map((document) => <li key={document.id}><b>{documentKindLabel[document.kind]}</b><span>{document.displayName}</span><code>{document.relativePath}</code></li>)}</ul>}</section>}
    {latest && <section className="order-document-card"><div className="order-document-heading"><div><span>Adatminőség és visszajelzés</span><h2>Hiba vagy hiány jelzése</h2><p>A jelzés a rendszerben követhető; az eredeti Excel/PDF forrás változatlan marad.</p></div></div>{role !== "reader" && <div className="order-document-form"><select value={feedbackCategory} onChange={(event) => setFeedbackCategory(event.target.value as OrderFeedbackCategory)}><option value="DATA_QUALITY">Hiányzó vagy hibás adat</option><option value="IMPORT_MAPPING">Import / forráseltérés</option><option value="DOCUMENT_REFERENCE">Dokumentumhivatkozás</option><option value="WORKFLOW">Határidő vagy folyamat</option></select><input value={feedbackMessage} onChange={(event) => setFeedbackMessage(event.target.value)} placeholder="Mi hibás vagy hiányzik?" /><button className="order-button order-button-secondary" onClick={() => void reportIssue()} disabled={reportFeedback.isPending}>Jelzés küldése</button></div>}{feedback.isLoading ? <p className="order-document-empty">Jelzések betöltése…</p> : !feedback.data?.length ? <p className="order-document-empty">Nincs nyitott vagy lezárt jelzés.</p> : <ul className="order-document-list">{feedback.data.map((item) => <li key={item.id}><b>{item.status === "RESOLVED" ? "Lezárt" : item.status === "ACKNOWLEDGED" ? "Nyugtázva" : "Nyitott"}</b><span>{item.category}: {item.message}</span>{item.resolution && <code>{item.resolution}</code>}{canPrepare && item.status !== "RESOLVED" && <button className="order-button order-button-secondary" onClick={() => void resolveFeedback.mutateAsync({ feedbackId: item.id, status: "RESOLVED", resolution: "Műszaki előkészítés lezárta." })}>Lezárás</button>}</li>)}</ul>}</section>}
    {message && <p className="order-document-message">{message}</p>}
    <section className="order-revision-list" aria-label="Rendelési revíziók">{order.revisions.map((revision) => <article className="order-revision" key={revision.id}><header><div><span>R{String(revision.revision).padStart(2, "0")}</span><h2>{revision.customerName}</h2></div><div className="order-register-states"><b className="order-intake-stage">{intakeLabel[revision.intakeStage]}</b><b className={`order-status order-status-${revision.status.toLowerCase()}`}>{statusLabel[revision.status]}</b></div></header><div className="order-revision-meta"><span>Vállalt szállítás: {revision.expectedDelivery ? new Intl.DateTimeFormat("hu-HU", { year: "numeric", month: "short", day: "numeric" }).format(new Date(revision.expectedDelivery)) : "nincs megadva"}</span><span>Prioritás: {revision.priority === 0 ? "normál" : `${revision.priority}.`}</span></div><div className="order-position-summary">{revision.positions.map((position) => <div key={position.id}><strong>{position.code}</strong><span>{position.name}</span><span>{position.quantity} db</span><span>{dimensions(position)}</span></div>)}</div><ManufacturedItemsPanel items={revision.manufacturedItems} canReview={canPrepare && revision.revision === latest.revision && revision.status === "DRAFT"} pending={reviewManufacturedItem.isPending} onReview={(itemId, state, resolution) => reviewManufacturedItem.mutateAsync({ itemId, state, resolution })} /><OrderPositionEvidenceList positions={revision.positions} canReview={canPrepare && revision.revision === latest.revision && (revision.status === "DRAFT" || revision.status === "REVIEW")} pending={resolveEvidence.isPending} onReview={(positionId, evidenceId, reviewState, resolution) => resolveEvidence.mutateAsync({ positionId, evidenceId, reviewState, resolution })} />{revision.audit.length > 0 && <div className="order-audit-list">{revision.audit.map((audit) => <div key={audit.id}><b>{audit.action === "APPROVED" ? "Jóváhagyva" : "Review-ra küldve"}</b><span>{audit.actorRole}</span><code>{audit.contentHash.slice(0, 12)}…</code><span>{audit.note || "—"}</span></div>)}</div>}</article>)}</section>
  </div></main>;
}
